### ISSUE TITLE
Patient - My Clinics - Check Screenshot - Get Direction is coming in the card

### ISSUE THREAD

**Issue by Arushi1390** [MaroofTech/Dr-plaza-issue#144]
![Screenshot (610)](https://user-images.githubusercontent.com/88670762/129315620-0da75936-6c08-42d2-8c35-dfc78f5741bd.png)

**Comment by MaroofTech** [comment]
@Arushi1390  Its a button and you can click on same and it will open the google map location. If any thing you need to change in term of UI reopen it and assign to @vayuzpriya
