### ISSUE TITLE
Admin > Notification Management > is not working - This module is to send notifications from Admin, but there is no filed for Patient's name, Patient Email id.

### ISSUE THREAD

**Issue by Arushi1390** [MaroofTech/Dr-plaza-issue#158]

**Comment by kanishkavayuz** [comment]
@Arushi1390 ,Currently the admin is sending the message to all the Patients/Doctors as it was discussed, need a confirmation on send message to send to individual

**Comment by kanishkavayuz** [comment]
@Arushi1390  please recheck the issue
