### ISSUE TITLE
Admin > Contact Us List > Can't see the Messages sent by Users

### ISSUE THREAD

**Issue by Arushi1390** [MaroofTech/Dr-plaza-issue#162]
![Screenshot (626)](https://user-images.githubusercontent.com/88670762/129442733-bc5e82b1-5037-4875-934e-396b79d5c0f3.png)

**Comment by kanishkavayuz** [comment]
@Arushi1390  fixed

**Comment by kanishkavayuz** [comment]
@Arushi1390 fixed
