### ISSUE TITLE
Toast message show 2 time

### ISSUE THREAD

**Issue by vayuzpriya** [MaroofTech/Dr-plaza-issue#178]
![Screenshot from 2021-08-17 18-02-02](https://user-images.githubusercontent.com/81085431/129726143-8f25a405-c0e3-4663-9752-7dc69b21c99d.png)

**Comment by kanishkavayuz** [comment]
@vayuzpriya  mam you have made favorite two corresponding clinics and that's why it's showing two corresponding clinics two messages.
