### ISSUE TITLE
Textual Issues - Admin

### ISSUE THREAD

**Issue by shivambhargava33** [MaroofTech/Dr-plaza-issue#232]
1. Staff - On clicking filter message should say - 'Please enter start and end date'
2. Add Staff - Assign Roles and Rights
3. Doctor - Filter by State - Increase Box Size
4. Appointments - Listing - 2nd Column - Correct Spelling of Appointment
5. Appointments - Listing - Last Column - Created At
6. Appointment Payments - Correct Spelling in Menu
7. Appointment Payments - 2nd Column of Table - Appointment ID - Correct Spelling
8. Report - Clinic Utilization - 4th and 5th Column of Table - Correct spelling of Vaccant to Vacant

**Comment by Arushi1390** [comment]
@kanishkavayuz
